Update jetty to 9.2.13
Version 9.3.5 didn't work with Spring on OpenJDK 7:
org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.

There was no problem when running on JDK 8.

https://travis-ci.org/cvut/zuul-oaas/jobs/89526430#L4244-L4297